# Generated by Django 5.2.8 on 2025-12-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_gmailtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_type', models.CharField(choices=[('once', 'Run Once'), ('daily', 'Every Day'), ('weekly', 'Specific Days of Week'), ('monthly_nth', 'Every Nth Day of Month'), ('yearly_nth', 'Nth Day of Month Once in Year')], max_length=20)),
                ('run_datetime', models.DateTimeField(blank=True, null=True)),
                ('run_time', models.TimeField(blank=True, null=True)),
                ('weekdays', models.JSONField(blank=True, null=True)),
                ('nth_day', models.PositiveIntegerField(blank=True, null=True)),
                ('month', models.PositiveIntegerField(blank=True, null=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
