# Generated by Django 6.0.2 on 2026-04-05 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('email_handler', '0002_emailtemplate'),
        ('org_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_type', models.CharField(choices=[('once', 'Run Once'), ('daily', 'Run Everyday'), ('weekly', 'Specific Days of Week'), ('monthly', 'Every Nth Day of Month'), ('yearly', 'Nth Day Once a Year')], max_length=10)),
                ('run_once_datetime', models.DateTimeField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('days_of_week', models.CharField(blank=True, help_text='Comma-separated day numbers (0=Sun, 1=Mon, ...)', max_length=15, null=True)),
                ('day_of_month', models.IntegerField(blank=True, help_text='Day of the month (1-31)', null=True)),
                ('yearly_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org_manager.group')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_handler.emailtemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
