# Generated by Django 6.0.2 on 2026-04-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedular', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailschedule',
            name='last_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
